// Purpose: Tests for schema validation, SVG structure, theme layout parity, renderer probing, failures, and browser geometry.
import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,chmod}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{cardGeometry,detectRenderer,renderCardPNG,renderCardSVG,validateVerdict}from'../src/index.mjs';import{cardGeometry as browserGeometry}from'../browser/card.js';
const verdict=(bars=[])=>({schemaVersion:1,title:'Verdict',headline:{label:'score',value:75,max:100},bars,footer:{model:'jev-1.13.0',generatedAt:'2026-09-21'}});
test('schema requires headline and caps bars',()=>{assert.throws(()=>validateVerdict({schemaVersion:1,title:'x',bars:[],footer:{model:'x',generatedAt:'x'}}),/headline/);assert.throws(()=>validateVerdict(verdict(Array.from({length:17},()=>({label:'x',value:.5})))),/16 bars/)});
test('SVG is self-contained for zero, one and max bars',()=>{for(const n of[0,1,16]){const svg=renderCardSVG(verdict(Array.from({length:n},(_,i)=>({label:`b${i}`,value:i/16}))));assert.match(svg,/^<svg xmlns=/);assert.match(svg,/<\/svg>$/);assert.doesNotMatch(svg,/(?:href|src)="https?:\/\//)}});
test('theme changes color tokens but not geometry',()=>{const v=verdict([{label:'x',value:.5}]),dark=renderCardSVG(v,'dark').replace(/#[0-9a-f]{6}/gi,'#COLOR'),light=renderCardSVG(v,'light').replace(/#[0-9a-f]{6}/gi,'#COLOR');assert.equal(dark,light)});
test('detects fake preferred renderer and none on empty path',async()=>{const d=await mkdtemp(join(tmpdir(),'card-')),p=join(d,'rsvg-convert');await writeFile(p,'#!/bin/sh\nexit 0\n');await chmod(p,0o755);assert.equal((await detectRenderer({path:d})).kind,'rsvg');assert.equal(await detectRenderer({path:''}),null)});
test('PNG surfaces renderer stderr',async()=>{await assert.rejects(()=>renderCardPNG(verdict(),'dark',{renderer:{kind:'rsvg',command:'/bin/sh'},timeoutMs:1000}),/renderer exited/)});
test('server and browser geometry agree',()=>assert.deepEqual(cardGeometry(6),browserGeometry(6)));
