// Purpose: Validate verdicts and render deterministic SVG or optional system-rendered PNG cards.
import{access,mkdtemp,readFile,rm,writeFile}from'node:fs/promises';import{delimiter,join}from'node:path';import{tmpdir}from'node:os';import{pathToFileURL}from'node:url';import{spawn}from'node:child_process';
export const themes={dark:{background:'#0b0f17',surface:'#1a2230',text:'#f7f2e8',muted:'#9ca8ba',accent:'#f3bd43',good:'#47d7a1'},light:{background:'#f8f3e9',surface:'#ded8cd',text:'#18202b',muted:'#667085',accent:'#e38b29',good:'#158f6b'}};
export function validateVerdict(v){if(!v||v.schemaVersion!==1||typeof v.title!=='string'||!v.headline||typeof v.headline.label!=='string'||!Number.isFinite(v.headline.value)||!Array.isArray(v.bars)||!v.footer||typeof v.footer.model!=='string'||typeof v.footer.generatedAt!=='string')throw new TypeError('verdict requires schemaVersion 1, title, headline, bars and footer');if(v.bars.length>16)throw new RangeError('at most 16 bars are supported');for(const b of v.bars)if(typeof b.label!=='string'||!Number.isFinite(b.value))throw new TypeError('each bar requires label and numeric value');return v}
export function cardGeometry(count){return{width:1080,height:Math.max(1080,420+count*48),bars:Array.from({length:count},(_,i)=>({x:330,y:330+i*48,width:680,height:22,labelX:54,labelY:347+i*48}))}}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function renderCardSVG(verdict,theme='dark'){validateVerdict(verdict);const palette=typeof theme==='string'?themes[theme]:theme;if(!palette)throw new TypeError('unknown theme');const g=cardGeometry(verdict.bars.length),max=verdict.headline.max??100,headline=Math.round(verdict.headline.value/max*100);const bars=verdict.bars.map((b,i)=>{const x=g.bars[i],v=Math.max(0,Math.min(1,b.value));return`<text x="${x.labelX}" y="${x.labelY}" class="label">${esc(b.label)}</text><rect x="${x.x}" y="${x.y}" width="${x.width}" height="${x.height}" rx="11" fill="${palette.surface}"/><rect x="${x.x}" y="${x.y}" width="${x.width*v}" height="${x.height}" rx="11" fill="${v>=.7?palette.good:palette.accent}"/><text x="1020" y="${x.labelY}" text-anchor="end" class="value">${Math.round(v*100)}</text>`}).join('');const citations=(verdict.citations||[]).slice(0,2).map((c,i)=>`<text x="54" y="${880+i*54}" class="quote">${esc(c.label)} — “${esc(c.quote).slice(0,90)}”</text>`).join('');return`<svg xmlns="http://www.w3.org/2000/svg" width="${g.width}" height="${g.height}" viewBox="0 0 ${g.width} ${g.height}"><rect width="100%" height="100%" fill="${palette.background}"/><style>.title{font:700 68px system-ui,sans-serif;fill:${palette.text}}.sub{font:24px system-ui,sans-serif;fill:${palette.muted}}.headline{font:800 112px system-ui,sans-serif;fill:${palette.accent}}.label,.value{font:20px system-ui,sans-serif;fill:${palette.text}}.quote{font:18px system-ui,sans-serif;fill:${palette.muted}}</style><text x="54" y="100" class="title">${esc(verdict.title)}</text>${verdict.subtitle?`<text x="54" y="145" class="sub">${esc(verdict.subtitle)}</text>`:''}<text x="54" y="270" class="headline">${headline}</text><text x="250" y="258" class="sub">${esc(verdict.headline.label)}</text>${bars}${citations}<text x="54" y="${g.height-50}" class="sub">${esc(verdict.footer.model)} · ${esc(verdict.footer.generatedAt)}${Number.isFinite(verdict.footer.estimatedCostUsd)?` · $${verdict.footer.estimatedCostUsd}`:''}</text></svg>`}
async function executable(name,pathValue){for(const dir of String(pathValue||'').split(delimiter).filter(Boolean)){const p=join(dir,name);try{await access(p);return p}catch{}}return null}
export async function detectRenderer({path=process.env.PATH}={}){for(const[name,kind]of[['rsvg-convert','rsvg'],['resvg','resvg'],['chromium','chrome'],['chromium-browser','chrome'],['google-chrome','chrome'],['chrome','chrome']]){const command=await executable(name,path);if(command)return{kind,command}}return null}
function run(command,args,{input,timeoutMs=15_000}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{stdio:['pipe','pipe','pipe']}),out=[],err=[];const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error(`renderer timed out after ${timeoutMs} ms`))},timeoutMs);child.stdout.on('data',x=>out.push(x));child.stderr.on('data',x=>err.push(x));child.on('error',e=>{clearTimeout(timer);reject(e)});child.on('close',code=>{clearTimeout(timer);code===0?resolve(Buffer.concat(out)):reject(new Error(`renderer exited ${code}: ${Buffer.concat(err).toString().trim()}`))});child.stdin.end(input)})}
export async function renderCardPNG(verdict,theme='dark',{renderer,timeoutMs=15_000}={}){const r=renderer??await detectRenderer();if(!r)throw new Error('No PNG renderer found; keep the SVG or install rsvg-convert, resvg, or Chromium.');const svg=renderCardSVG(verdict,theme);if(r.kind==='rsvg')return run(r.command,['--format','png'],{input:svg,timeoutMs});if(r.kind==='resvg')return run(r.command,['-','-'],{input:svg,timeoutMs});const directory=await mkdtemp(join(tmpdir(),'jev-cardgen-')),source=join(directory,'card.svg'),target=join(directory,'card.png'),height=cardGeometry(verdict.bars.length).height;try{await writeFile(source,svg);await run(r.command,['--headless=new','--disable-gpu','--no-sandbox','--hide-scrollbars',`--window-size=1080,${height}`,`--screenshot=${target}`,pathToFileURL(source).href],{input:'',timeoutMs});return await readFile(target)}finally{await rm(directory,{recursive:true,force:true})}}
export async function renderFile(input,out,{theme='dark',png}={}){const v=JSON.parse(await readFile(input,'utf8')),svg=renderCardSVG(v,theme);await writeFile(out,svg);let pngResult=null;if(png){const renderer=await detectRenderer();if(renderer){await writeFile(png,await renderCardPNG(v,theme,{renderer}));pngResult=png}}return{svg:out,png:pngResult}}
